name: taskmanager
description: "Task Manager"

publish_to: "none" # Remove this line if you wish to
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  injectable: ^2.5.0
  injectable_generator: ^2.6.2
  json_serializable: ^6.9.0
  dio: ^5.8.0+1
  permission_handler: ^12.0.1
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  flutter_svg: ^2.0.17
  toastification: ^3.0.0
  gap: ^3.0.1
  flutter_svg_provider: ^1.0.7
  get_it: ^8.0.2
  dartz: ^0.10.1
  pretty_logger: ^1.0.0
  go_router: ^14.6.2
  freezed_annotation: ^2.4.4
  string_ext: ^0.2.0
  flutter_bounce: ^1.1.0
  image_picker: ^1.0.4
  file_picker: ^10.3.1
  flutter_bloc: ^9.1.1
  bloc: ^9.0.0
  hive_flutter: ^1.1.0
  firebase_database: ^12.0.0
  firebase_auth: ^6.0.1
  flutter_secure_storage: ^9.2.4
  firebase_core: ^4.0.0
  hive: ^2.2.3
  hive_generator: ^2.0.1
  connectivity_plus: ^6.1.5

dev_dependencies:
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.14.2
  flutter_gen_runner: ^5.9.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^2.5.7
  mockito: ^5.4.5
  change_app_package_name: ^1.5.0
  hive_test: ^1.0.1

dependency_overrides:
  intl: 0.20.0
  web: 1.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
