// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2EZYSoVGFSOWJfYpsN_g5hAof4YysEZo',
    appId: '1:400007114788:android:30750b460bd6613097e8b1',
    messagingSenderId: '400007114788',
    projectId: 'taskmanager-56860',
    databaseURL: 'https://taskmanager-56860-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'taskmanager-56860.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPFqkj8GsQEXaDslvPb3TDUy0n0TR34LE',
    appId: '1:400007114788:ios:c0b0659861d1628997e8b1',
    messagingSenderId: '400007114788',
    projectId: 'taskmanager-56860',
    databaseURL: 'https://taskmanager-56860-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'taskmanager-56860.firebasestorage.app',
    iosBundleId: 'com.lukas.taskmanager',
  );

}