name: Flutter CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Setup Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.3"
          cache: true

      # Install dependencies
      - name: Install Dependencies
        run: flutter pub get

      # Run build_runner to check generated files
      - name: Build (optional)
        run: flutter pub run build_runner build --delete-conflicting-outputs

      # Analyze
      - name: Run Analyzer
        run: flutter analyze

      # Run tests
      - name: Run Unit Tests
        run: flutter test
